DROP DATABASE IF EXISTS `DAI`;
CREATE DATABASE DAI;

USE  DAI;

DROP TABLE IF EXISTS `TIPOANALISIS`;
CREATE TABLE TIPOANALISIS(
`	idTipoAnalisis` INT PRIMARY KEY NOT NULL,
`nombre` VARCHAR(45) NOT NULL
);

DROP TABLE IF EXISTS `USUARIO`;
CREATE TABLE `USUARIO` (
  `codigoUsuario` VARCHAR(10) NOT NULL,
  `nombreUsuario` VARCHAR(30) NOT NULL,
  `TipoUsuario` VARCHAR(15) NOT NULL,
	`passwordUsuario`VARCHAR(15) NOT NULL,
  `EstadoUsuario` CHAR(3) DEFAULT 'INH',
  PRIMARY KEY (`codigoUsuario`)
);

DROP TABLE IF EXISTS `PARTICULAR`;
CREATE TABLE PARTICULAR(
  `codigoParticular` VARCHAR(10) PRIMARY KEY,
  `rutParticular` VARCHAR(45) NOT NULL,
  `nombreParticular` VARCHAR(45) NOT NULL,
  `direccionParticular` VARCHAR(45) NOT NULL,
  `emailParticular` VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS `EMPRESA`;
CREATE TABLE EMPRESA(
  `codigoEmpresa` VARCHAR(10) PRIMARY KEY NOT NULL,
  `rutEmpresa` VARCHAR(30) NOT NULL,
  `direccionEmpresa` VARCHAR(50) NOT NULL,
CONSTRAINT empresa_usuario_fk FOREIGN KEY (codigoEmpresa) REFERENCES USUARIO(codigoUsuario)
);

DROP TABLE IF EXISTS `EMPLEADO`;
CREATE TABLE `EMPLEADO` (
  `rutEmpleado` VARCHAR(10) PRIMARY KEY NOT NULL,
  `nombreEmpleado` VARCHAR(50) NOT NULL,
  `categoria` CHAR NOT NULL
);

DROP TABLE IF EXISTS `CONTACTO`;
CREATE TABLE CONTACTO(
	`rutContacto` VARCHAR(10) PRIMARY KEY NOT NULL,
  `nombreContacto` VARCHAR(30) NOT NULL,
  `emailContacto` VARCHAR(45) NOT NULL,
  `telefonoContacto` VARCHAR(15) ,
  `Empresa_codigoEmpresa` VARCHAR(10) NOT NULL,
  CONSTRAINT contacto_empresa_fk FOREIGN KEY (Empresa_codigoEmpresa) REFERENCES EMPRESA(codigoEmpresa)
);


DROP TABLE IF EXISTS `ANALISISMUESTRAS`;
CREATE TABLE ANALISISMUESTRAS(
	`idAnalisisMuestras` INT PRIMARY KEY NOT NULL,
  `fechaRecepcion` DATE NOT NULL,
  `temperaturaMuestra` DECIMAL(3,1) NOT NULL,
  `cantidadMuestra` INT NOT NULL,
  `Empresa_codigoEmpresa` VARCHAR(10) NOT NULL,
  `Particular_codigoParticular` VARCHAR(10) NOT NULL,
  `rutEmpleadoRecibe` VARCHAR(10) NOT NULL,
  CONSTRAINT EMPRESA_ANALISIS_FK FOREIGN KEY (Empresa_codigoEmpresa) REFERENCES EMPRESA(codigoEmpresa),
  CONSTRAINT PARTICULAR_ANALISIS_FK FOREIGN KEY (Particular_codigoParticular) REFERENCES PARTICULAR(codigoParticular),
  CONSTRAINT EMPLEADO_ANALISIS_FK FOREIGN KEY (rutEmpleadoRecibe) REFERENCES EMPLEADO(rutEmpleado)
  
);

DROP TABLE IF EXISTS `RESULTADOANALISIS`;
CREATE TABLE RESULTADOANALISIS(
	`idTipoAnalisis` INT NOT NULL,
  `idAnalisisMuestras` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `PPM` INT NOT NULL,
  `estado` BIT NOT NULL,
  `rutEmpleadoAnalista` VARCHAR(10)
);

DROP TABLE IF EXISTS `TELEFONO`;
CREATE TABLE TELEFONO(
	`idTelefono` INT PRIMARY KEY NOT NULL,
  `numeroTelefono` VARCHAR(20) NOT NULL,
  `Particular_codigoParticular` VARCHAR(10) NOT NULL,
  CONSTRAINT TELEFONO_PARTICULAR_FK FOREIGN KEY (Particular_codigoParticular) REFERENCES PARTICULAR(codigoParticular)
);
